export const ERROR_CODES = {
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_INACTIVE: 'PLAN_INACTIVE',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  COURSE_CREATION_LIMIT_REACHED: 'COURSE_CREATION_LIMIT_REACHED',
  PAID_COURSE_NOT_ALLOWED: 'PAID_COURSE_NOT_ALLOWED',
  STUDENT_LIMIT_REACHED: 'STUDENT_LIMIT_REACHED',
  STORAGE_LIMIT_REACHED: 'STORAGE_LIMIT_REACHED',
  LIVE_CLASS_LIMIT_REACHED: 'LIVE_CLASS_LIMIT_REACHED',
  PLAN_ALREADY_EXISTS: 'PLAN_ALREADY_EXISTS',
  INVALID_PLAN_CONFIGURATION: 'INVALID_PLAN_CONFIGURATION',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
