import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    include: ['tests/**/*.test.ts'],
    exclude: ['node_modules', 'dist', 'coverage', 'coverage-vitest', 'src/**'],
    setupFiles: ['./tests/setup/env.ts', './tests/setup/setup.ts'],
    globalSetup: ['./tests/setup/global-setup.ts'],
    globalTeardown: ['./tests/setup/global-teardown.ts'],
    restoreMocks: true,
    clearMocks: true,
    testTimeout: 10000,
    hookTimeout: 15000,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'json'],
      reportsDirectory: 'coverage-vitest',
      include: [
        'src/middlewares/**',
        'src/validators/**',
        'src/utils/**',
        'src/services/auth.service.ts',
        'src/services/token.service.ts',
        'src/services/payment.service.ts',
        'src/services/course.service.ts',
        'src/services/platformSettings.service.ts',
        'src/services/subscriptionPermission.service.ts',
        'src/controllers/auth.controller.ts',
      ],
      exclude: [
        'src/**/*.d.ts',
        'src/cache/**',
        'src/config/**',
        'src/constants/**',
        'src/interfaces/**',
        'src/models/**',
        'src/routes/**',
        'src/test/**',
        'src/types/**',
        'src/__tests__/**',
        'src/services/affiliate.service.ts',
        'src/services/cascadeDelete.service.ts',
        'src/services/revenue.service.ts',
        'src/utils/logger.ts',
        'src/utils/pdfGenerator.ts',
        'src/utils/sendEmail.ts',
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
        'src/services/payment.service.ts': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/services/token.service.ts': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/middlewares/**': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/utils/generateToken.ts': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/utils/certificate.ts': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/utils/certificateIdGenerator.ts': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/utils/grading.ts': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/utils/escapeRegex.ts': { statements: 95, branches: 95, functions: 95, lines: 95 },
        'src/controllers/auth.controller.ts': { statements: 90, branches: 90, functions: 90, lines: 90 },
      },
    },
  },
});
